import os
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    DATABASE_URL = "sqlite:///./test.db"

engine = create_engine(DATABASE_URL)

def run_migration():
    with engine.connect() as conn:
        print("Creating comments table...")
        try:
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS comments (
                    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
                    lesson_id INTEGER REFERENCES lessons(id) ON DELETE CASCADE,
                    content TEXT NOT NULL,
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    parent_id INTEGER REFERENCES comments(id) ON DELETE CASCADE
                );
            """))
            print("- Created comments table.")
        except Exception as e:
            print(f"- Error creating comments table: {e}")
            
        conn.commit()
        print("Migration complete.")

if __name__ == "__main__":
    run_migration()
