-- DANGER: This script will DROP all existing tables and data.
-- Run this in the Supabase SQL Editor to reset your database to the new schema.

-- 1. Drop existing tables (Reverse order of dependencies)
DROP TABLE IF EXISTS submissions CASCADE;
DROP TABLE IF EXISTS challenges CASCADE;
DROP TABLE IF EXISTS user_tasks CASCADE; -- Legacy table
DROP TABLE IF EXISTS lessons CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;

-- 2.-- Create Enum Type for User Roles
CREATE TYPE "UserRole" AS ENUM ('student', 'admin', 'instructor', 'support');

-- Users Table
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    hashed_password TEXT,
    full_name TEXT,
    avatar_url TEXT,
    role "UserRole" DEFAULT 'student',
    is_active BOOLEAN DEFAULT TRUE,
    google_sub TEXT UNIQUE,
    current_streak INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Courses Table
CREATE TYPE "CourseType" AS ENUM ('one_on_one', 'group', 'pre_recorded');

CREATE TABLE courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    slug TEXT UNIQUE NOT NULL,
    thumbnail_url TEXT,
    is_published BOOLEAN DEFAULT FALSE,
    instructor_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    course_type "CourseType" DEFAULT 'pre_recorded'
);

-- 5. Create Lessons Table
CREATE TABLE lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    video_url TEXT,
    content TEXT,
    order_index INTEGER NOT NULL
);

-- 6. Create Challenges Table
CREATE TABLE challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT NOT NULL UNIQUE REFERENCES lessons(id) ON DELETE CASCADE,
    slug TEXT UNIQUE NOT NULL,
    problem_statement TEXT NOT NULL,
    starter_code TEXT,
    test_cases JSONB -- Using JSONB for Postgres
);

-- 7. Create Submissions Table
CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    challenge_id BIGINT NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
    code_submitted TEXT NOT NULL,
    status TEXT NOT NULL,
    passed_test_cases INTEGER DEFAULT 0,
    total_test_cases INTEGER DEFAULT 0,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Seed Default Data (Optional but recommended)
INSERT INTO courses (title, slug, thumbnail_url, description, is_published) VALUES
('Python for Beginners', 'python-for-beginners', 'https://bit.ly/3tjd7x3', 'Start your coding journey with Python.', TRUE),
('Advanced Robotics', 'advanced-robotics', 'https://bit.ly/3RO0H4S', 'Master robotics with advanced algorithms.', TRUE);

-- Insert Lessons for Python Course
WITH py_course AS (SELECT id FROM courses WHERE slug = 'python-for-beginners')
INSERT INTO lessons (course_id, title, video_url, content, order_index) VALUES
((SELECT id FROM py_course), 'Intro to Python', 'https://www.youtube.com/watch?v=kqtD5dpn9C8', 'Welcome to the course!', 1),
((SELECT id FROM py_course), 'Variables & Types', 'https://www.youtube.com/watch?v=rfscVS0vtbw', 'Learn about data types.', 2);

-- Insert Challenges
WITH l1 AS (SELECT id FROM lessons WHERE title = 'Intro to Python')
INSERT INTO challenges (lesson_id, slug, problem_statement, starter_code, test_cases) VALUES
((SELECT id FROM l1), 'python-intro-c1', 'Print "Hello World"', 'print("Hello World")', '[{"input": "", "expected_output": "Hello World"}]'::jsonb);
