"""add stdout stderr

Revision ID: f7ae26a1416d
Revises: 
Create Date: 2026-01-10 17:08:42.852891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7ae26a1416d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('submissions', sa.Column('stdout', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('stderr', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_column('submissions', 'stderr')
    op.drop_column('submissions', 'stdout')
    # ### end Alembic commands ###
